AllCops:
  Exclude:
    - "vendor/**/*"
  DisplayCopNames: true

Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 7

Style/AccessorMethodName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  MinBodyLength: 4

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/PredicateName:
  NamePrefixBlacklist:
    - "is_"
    - "have_"

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceBeforeComma:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
   EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
    - "idcf-your.gemspec"
    - "spec/**/*"
